"use client";

import Head from "next/head";
import About from "@/components2/About";
import { useRouter } from "next/router";
import Hero from "@/components/UI/Hero";
import Carousel from "@/components2/Carousel";
import Contact from "@/components/UI/Contact";
import Services from "@/components/UI/Services";
import LatestNews from "@/components2/LatestNews";
import Portfolio from "@/components/UI/Portfolio";

const Home = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Hero page={router.pathname} />
      <About />
      <Services />
      <Portfolio />
      <LatestNews />
      <Carousel />
      <Contact />
    </>
  );
};

export default Home;
